sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: h4K40ikSoXcjUUE8A5sJSEznMmaqwMFB5mUINSN0v38V7VXypWWZROF7qnUGrN1nCWEaUtgXMEOnM/YAjIiQjrph5Lx/sJEY+qi6WwLTaWZ8u01VoaeaxMC+wToOfUOaBv55At7HtUGKpOCrlJDXdcw4hQ1XOiHeuyENJMosMixmkD1zbX12N0ndLXGOVexZ95RvzbVecq7Iv4AEyO598bBXF7kQyOiGJPFf0Wf8WuZtI0N7UVZueLn2iEFWHcpjXNc7reE2TVTStW+G6anyTMhisBXXmuoCZx6J+Gnb5C46mVlWjIrPM+t8tsh3ZzwZAPIjKHgxlFJ8gStocKAcWXqmon+8ZWkU2kNEsuH//YrnJKMG7Lrdq/zGMgdq6vUgjechCIgZyO6dwR52n0KfSZaOmGr/S57MU9jXRjE35JRlRDfFp/mXneGt9LsvCpK8oPha+s6EAnlvbhrHaIAzOaSaOk7NtY3Wu77YzSfCbRfbeFqiFSNIzzmxDOdOCwNSN9hENd04a1EPM5ZrLJ3tThNclNSjv4lzac5eXWNMM6vPet+TOLcLgleg2PFXtu4Ql/3SrMHNXb9+MjfmusdL4XZ+ivDWpc4bBVg9HXUzy37V8A46gxkPsLq5RObE6h2p+u/fbdXo4hyvEmxpaVmOekjz+J1NJ6aOhn8BxeOYoO8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Woman-s-Trials--Or-Tales-and-Sketches-from-the-Life-around-Us_4617
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy